services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    restart: always
    command: ["./bin/rails", "server", "-p", "80", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: production
      PORT: 80
      DATABASE_URL: mysql2://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    expose:
      - "80"
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  db:
    image: mysql:8.0
    restart: always
    command: 
      - --performance_schema=OFF
      - --innodb_buffer_pool_size=64M
      - --innodb_log_buffer_size=1M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  caddy_data:
  caddy_config:
