FROM ruby:3.4.8

# コンテナの作業ディレクトリ
WORKDIR /app

# コンテナの作業ディレクトリにコピー
COPY Gemfile Gemfile.lock /app/

# 依存関係をインストール
RUN bundle install

COPY entrypoint.sh /usr/bin/entrypoint.sh
# プロジェクト作成時はコメントアウト（コンテナが立ち上がらないため）
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

# プロジェクト作成時はCMDをコメントアウト（コンテナが立ち上がらないため）
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
