# Name of your application. Used to uniquely configure containers.
service: manage-pantry

# Name of the container image (use your-user/app-name on external registries).
image: <%= ENV['DOCKER_HUB_USERNAME'] %>/manage-pantry

# Deploy to these servers.
servers:
  web:
    - <%= ENV['SERVER_IP'] %>

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: <%= ENV['APP_DOMAIN'] %>
  healthcheck:
    path: /up
    port: 3000
    interval: 5s

# Where you keep your container images.
registry:
  server: docker.io
  username: <%= ENV['DOCKER_HUB_USERNAME'] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_REDIRECT_URI
  clear:
    MYSQL_HOST: manage-pantry-db
    MYSQL_PORT: 3306
    SOLID_QUEUE_IN_PUMA: true

# Use a persistent storage volume
volumes:
  - "manage_pantry_storage:/rails/storage"

# Configure the image builder.
builder:
  arch: amd64

# Use accessory services (MySQL)
accessories:
  db:
    image: mysql:8.0
    host: <%= ENV['SERVER_IP'] %>
    port: "3306:3306"
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    directories:
      - data:/var/lib/mysql
